"""Initial migration

Revision ID: 1e0dddbf5184
Revises: 
Create Date: 2025-09-26 23:50:23.322805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0dddbf5184'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telecom_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zid_number', sa.Integer(), nullable=False),
    sa.Column('lat_bot_left', sa.Float(), nullable=False),
    sa.Column('long_bot_left', sa.Float(), nullable=False),
    sa.Column('lat_bot_right', sa.Float(), nullable=False),
    sa.Column('long_bot_right', sa.Float(), nullable=False),
    sa.Column('lat_top_right', sa.Float(), nullable=False),
    sa.Column('long_top_right', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zid_number')
    )
    op.create_index(op.f('ix_telecom_grids_id'), 'telecom_grids', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grid_id', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['telecom_grids.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_table('telecom_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=False),
    sa.Column('time_hour', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['telecom_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telecom_stats_id'), 'telecom_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telecom_stats_id'), table_name='telecom_stats')
    op.drop_table('telecom_stats')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telecom_grids_id'), table_name='telecom_grids')
    op.drop_table('telecom_grids')
    # ### end Alembic commands ###
